[workspace]
members = [
    "integration-lib",
    "program",
    "program_v2",
]

[profile.release]
lto = true

[profile.test]
opt-level = 2

[patch."https://github.com/identity-com/cruiser"]
cruiser = { path = "../../cruiser" }
